import {
  CREATE_POST_MUTATION,
  DELETE_POST_MUTATION,
  FETCH_POST_QUERY,
  FETCH_POSTS_QUERY,
} from "./posts";
import { LIKE_POST_MUTATION } from "./likes";
import { CREATE_COMMENT_MUTATION, DELETE_COMMENT_MUTATION } from "./comments";
import { LOGIN_USER, REGISTER_USER } from "./users";

export {
  CREATE_POST_MUTATION,
  DELETE_POST_MUTATION,
  FETCH_POST_QUERY,
  FETCH_POSTS_QUERY,
  LIKE_POST_MUTATION,
  CREATE_COMMENT_MUTATION,
  DELETE_COMMENT_MUTATION,
  LOGIN_USER,
  REGISTER_USER,
};
